[book]
authors = ["LIAO — Liga Acadêmica de IA e Otimização"]
language = "pt"
src = "src"
title = "Olho na Caixa"

[output.html]
git-repository-url = "https://github.com/LIAO-Liga-Academica-de-IA-e-Otimizacao/olho-na-caixa"
